-- Create function for mertsightsAI to execute raw SQL queries
-- This enables the RAG system to run dynamic queries generated by Gemini

CREATE OR REPLACE FUNCTION execute_sql(query text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER  -- Run with function owner's privileges
AS $$
DECLARE
    result json;
BEGIN
    -- Security check: ensure query starts with SELECT
    IF query !~* '^\s*SELECT' THEN
        RAISE EXCEPTION 'Only SELECT queries are allowed';
    END IF;
    
    -- Execute query and return as JSON
    EXECUTE 'SELECT json_agg(row_to_json(t)) FROM (' || query || ') t' INTO result;
    
    -- Return empty array if no results
    IF result IS NULL THEN
        result := '[]'::json;
    END IF;
    
    RETURN result;
END;
$$;

-- Grant execute permission to authenticated users
GRANT EXECUTE ON FUNCTION execute_sql(text) TO authenticated;
GRANT EXECUTE ON FUNCTION execute_sql(text) TO anon;

-- Add comment
COMMENT ON FUNCTION execute_sql(text) IS 'Execute read-only SQL queries for mertsightsAI analytics. Only SELECT statements allowed.';
